name: android CI/CD

on:
  push:
    branches:
      - master
jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter --version

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0  # Adjust Ruby version as needed

      - name: Install Bundler
        run: gem install bundler

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v2

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Check Fastlane version
        run: fastlane --version

#      - name: Build And Test
#        run: fastlane android build_and_test

      - name: Unit Test
        run: cd android && fastlane unit_test_and_build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: apk-artifact
          path: apk/


