name: android CI/CD

on:
  push:
    branches:
      - master
jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter --version

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0  # Adjust Ruby version as needed

      - name: Install Bundler
        run: gem install bundler

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Check Fastlane version
        run: fastlane --version

#      - name: Build And Test
#        run: fastlane android build_and_test

      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew


      - name: Unit Test
        run: cd android && ./gradlew app:assembleDebug && fastlane unit_test_and_build

      - name: Create APK Directory
        run: mkdir -p test_apk


