name: android CI/CD
uses: subosito/flutter-action@v2.10.0

on:
  push:
    branches:
      - master
jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0  # Adjust Ruby version as needed

      - name: Install Bundler
        run: gem install bundler

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Check Fastlane version
        run: fastlane --version

#      - name: Build And Test
#        run: fastlane android build_and_test

      - name: Unit Test
        run: cd android && fastlane unit_test

